### ISSUE TITLE
Infografía Gestión de proyectos

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/infografia-MariaC232-1#2]
[Gestion de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-MariaC232-1/files/7117502/Gestion.de.proyectos.de.software.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Falta la metodologías y herramientas. Bien hecho y revisado.
